#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# nix-shell $DIR/default.nix -A shells.ghc --add-root $DIR/dist-newstyle/gc-roots/gc-root --indirect
nix-shell $DIR/default-spec.nix -A shells.ghc --add-root $DIR/dist-newstyle/gc-roots/gc-root --indirect
